//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace VS2010.ConsoleApp.Test.Tree {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SearchableServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SearchableService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getIndexDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback setIndexDataFlagOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSearchDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback setDataStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SearchableService() {
            this.Url = global::VS2010.ConsoleApp.Test.Properties.Settings.Default.VS2010_ConsoleApp_Test_Tree_SearchableService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getIndexDataCompletedEventHandler getIndexDataCompleted;
        
        /// <remarks/>
        public event setIndexDataFlagCompletedEventHandler setIndexDataFlagCompleted;
        
        /// <remarks/>
        public event getSearchDataCompletedEventHandler getSearchDataCompleted;
        
        /// <remarks/>
        public event setDataStatusCompletedEventHandler setDataStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getIndexData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getIndexData(string dbid, string tableName, string id, bool all, int pageSize, int pageIndex) {
            object[] results = this.Invoke("getIndexData", new object[] {
                        dbid,
                        tableName,
                        id,
                        all,
                        pageSize,
                        pageIndex});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getIndexDataAsync(string dbid, string tableName, string id, bool all, int pageSize, int pageIndex) {
            this.getIndexDataAsync(dbid, tableName, id, all, pageSize, pageIndex, null);
        }
        
        /// <remarks/>
        public void getIndexDataAsync(string dbid, string tableName, string id, bool all, int pageSize, int pageIndex, object userState) {
            if ((this.getIndexDataOperationCompleted == null)) {
                this.getIndexDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetIndexDataOperationCompleted);
            }
            this.InvokeAsync("getIndexData", new object[] {
                        dbid,
                        tableName,
                        id,
                        all,
                        pageSize,
                        pageIndex}, this.getIndexDataOperationCompleted, userState);
        }
        
        private void OngetIndexDataOperationCompleted(object arg) {
            if ((this.getIndexDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getIndexDataCompleted(this, new getIndexDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setIndexDataFlag", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int setIndexDataFlag(string dbid, string tableName, string transactionId) {
            object[] results = this.Invoke("setIndexDataFlag", new object[] {
                        dbid,
                        tableName,
                        transactionId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void setIndexDataFlagAsync(string dbid, string tableName, string transactionId) {
            this.setIndexDataFlagAsync(dbid, tableName, transactionId, null);
        }
        
        /// <remarks/>
        public void setIndexDataFlagAsync(string dbid, string tableName, string transactionId, object userState) {
            if ((this.setIndexDataFlagOperationCompleted == null)) {
                this.setIndexDataFlagOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetIndexDataFlagOperationCompleted);
            }
            this.InvokeAsync("setIndexDataFlag", new object[] {
                        dbid,
                        tableName,
                        transactionId}, this.setIndexDataFlagOperationCompleted, userState);
        }
        
        private void OnsetIndexDataFlagOperationCompleted(object arg) {
            if ((this.setIndexDataFlagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setIndexDataFlagCompleted(this, new setIndexDataFlagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSearchData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getSearchData(string tableName, string returnFields, string ids, bool isDetail) {
            object[] results = this.Invoke("getSearchData", new object[] {
                        tableName,
                        returnFields,
                        ids,
                        isDetail});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSearchDataAsync(string tableName, string returnFields, string ids, bool isDetail) {
            this.getSearchDataAsync(tableName, returnFields, ids, isDetail, null);
        }
        
        /// <remarks/>
        public void getSearchDataAsync(string tableName, string returnFields, string ids, bool isDetail, object userState) {
            if ((this.getSearchDataOperationCompleted == null)) {
                this.getSearchDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSearchDataOperationCompleted);
            }
            this.InvokeAsync("getSearchData", new object[] {
                        tableName,
                        returnFields,
                        ids,
                        isDetail}, this.getSearchDataOperationCompleted, userState);
        }
        
        private void OngetSearchDataOperationCompleted(object arg) {
            if ((this.getSearchDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSearchDataCompleted(this, new getSearchDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setDataStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int setDataStatus(string tableName, string ids) {
            object[] results = this.Invoke("setDataStatus", new object[] {
                        tableName,
                        ids});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void setDataStatusAsync(string tableName, string ids) {
            this.setDataStatusAsync(tableName, ids, null);
        }
        
        /// <remarks/>
        public void setDataStatusAsync(string tableName, string ids, object userState) {
            if ((this.setDataStatusOperationCompleted == null)) {
                this.setDataStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetDataStatusOperationCompleted);
            }
            this.InvokeAsync("setDataStatus", new object[] {
                        tableName,
                        ids}, this.setDataStatusOperationCompleted, userState);
        }
        
        private void OnsetDataStatusOperationCompleted(object arg) {
            if ((this.setDataStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setDataStatusCompleted(this, new setDataStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getIndexDataCompletedEventHandler(object sender, getIndexDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getIndexDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getIndexDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setIndexDataFlagCompletedEventHandler(object sender, setIndexDataFlagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setIndexDataFlagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setIndexDataFlagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getSearchDataCompletedEventHandler(object sender, getSearchDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSearchDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSearchDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setDataStatusCompletedEventHandler(object sender, setDataStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setDataStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setDataStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591