//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VS2010.ConsoleApp.Test.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.30.89:8090/vipCloud/service/WsdlSearchable")]
        public string VS2010_ConsoleApp_Test_WebReference_WsdlSearchable {
            get {
                return ((string)(this["VS2010_ConsoleApp_Test_WebReference_WsdlSearchable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.20.24:20001/WebServiceWithSoapHeader.asmx")]
        public string VS2010_ConsoleApp_Test_WebServiceHeaderTest_WebServiceWithSoapHeader {
            get {
                return ((string)(this["VS2010_ConsoleApp_Test_WebServiceHeaderTest_WebServiceWithSoapHeader"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.irtree.cn:94/SearchableService.asmx")]
        public string VS2010_ConsoleApp_Test_Tree_SearchableService {
            get {
                return ((string)(this["VS2010_ConsoleApp_Test_Tree_SearchableService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.20.24:8090/userManager/vipCloud/webService/ReaderInfo")]
        public string VS2010_ConsoleApp_Test_ReaderInfoService_ReaderInfoService {
            get {
                return ((string)(this["VS2010_ConsoleApp_Test_ReaderInfoService_ReaderInfoService"]));
            }
        }
    }
}
