//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace VS2010.ConsoleApp.Test.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsdlSearchableHttpBinding", Namespace="http://wsdl.search.module.cloud.vip.com")]
    public partial class WsdlSearchable : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback vipMultiObjectSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback vipCluserOperationCompleted;
        
        private System.Threading.SendOrPostCallback customDataRetrieveOperationOperationCompleted;
        
        private System.Threading.SendOrPostCallback customRegionChangeNoticeOperationCompleted;
        
        private System.Threading.SendOrPostCallback vipSearchByRealtionOperationCompleted;
        
        private System.Threading.SendOrPostCallback customDataUpadteOpreationOperationCompleted;
        
        private System.Threading.SendOrPostCallback customDataDeleteOperationOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTokenStreamOperationCompleted;
        
        private System.Threading.SendOrPostCallback hasKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVisCacheOperationCompleted;
        
        private System.Threading.SendOrPostCallback vipGetInfoByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSuggestOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteVisCacheOperationCompleted;
        
        private System.Threading.SendOrPostCallback reCreateTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback userDataChangedNotifiedOperationCompleted;
        
        private System.Threading.SendOrPostCallback vipGetPartInfoByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback vipSearchByObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback changeSolrIndexRootPathOperationCompleted;
        
        private System.Threading.SendOrPostCallback vipSearchByResultsOperationCompleted;
        
        private System.Threading.SendOrPostCallback setVisCacheOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsdlSearchable() {
            this.Url = global::VS2010.ConsoleApp.Test.Properties.Settings.Default.VS2010_ConsoleApp_Test_WebReference_WsdlSearchable;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event vipMultiObjectSearchCompletedEventHandler vipMultiObjectSearchCompleted;
        
        /// <remarks/>
        public event vipCluserCompletedEventHandler vipCluserCompleted;
        
        /// <remarks/>
        public event customDataRetrieveOperationCompletedEventHandler customDataRetrieveOperationCompleted;
        
        /// <remarks/>
        public event customRegionChangeNoticeCompletedEventHandler customRegionChangeNoticeCompleted;
        
        /// <remarks/>
        public event vipSearchByRealtionCompletedEventHandler vipSearchByRealtionCompleted;
        
        /// <remarks/>
        public event customDataUpadteOpreationCompletedEventHandler customDataUpadteOpreationCompleted;
        
        /// <remarks/>
        public event customDataDeleteOperationCompletedEventHandler customDataDeleteOperationCompleted;
        
        /// <remarks/>
        public event getTokenStreamCompletedEventHandler getTokenStreamCompleted;
        
        /// <remarks/>
        public event hasKeyCompletedEventHandler hasKeyCompleted;
        
        /// <remarks/>
        public event getVisCacheCompletedEventHandler getVisCacheCompleted;
        
        /// <remarks/>
        public event vipGetInfoByIdCompletedEventHandler vipGetInfoByIdCompleted;
        
        /// <remarks/>
        public event getSuggestCompletedEventHandler getSuggestCompleted;
        
        /// <remarks/>
        public event deleteVisCacheCompletedEventHandler deleteVisCacheCompleted;
        
        /// <remarks/>
        public event reCreateTableCompletedEventHandler reCreateTableCompleted;
        
        /// <remarks/>
        public event userDataChangedNotifiedCompletedEventHandler userDataChangedNotifiedCompleted;
        
        /// <remarks/>
        public event vipGetPartInfoByIdCompletedEventHandler vipGetPartInfoByIdCompleted;
        
        /// <remarks/>
        public event vipSearchByObjectCompletedEventHandler vipSearchByObjectCompleted;
        
        /// <remarks/>
        public event changeSolrIndexRootPathCompletedEventHandler changeSolrIndexRootPathCompleted;
        
        /// <remarks/>
        public event vipSearchByResultsCompletedEventHandler vipSearchByResultsCompleted;
        
        /// <remarks/>
        public event setVisCacheCompletedEventHandler setVisCacheCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string vipMultiObjectSearch([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2) {
            object[] results = this.Invoke("vipMultiObjectSearch", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void vipMultiObjectSearchAsync(string in0, string in1, string in2) {
            this.vipMultiObjectSearchAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void vipMultiObjectSearchAsync(string in0, string in1, string in2, object userState) {
            if ((this.vipMultiObjectSearchOperationCompleted == null)) {
                this.vipMultiObjectSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvipMultiObjectSearchOperationCompleted);
            }
            this.InvokeAsync("vipMultiObjectSearch", new object[] {
                        in0,
                        in1,
                        in2}, this.vipMultiObjectSearchOperationCompleted, userState);
        }
        
        private void OnvipMultiObjectSearchOperationCompleted(object arg) {
            if ((this.vipMultiObjectSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vipMultiObjectSearchCompleted(this, new vipMultiObjectSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string vipCluser([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, int in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in5, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in6, int in7, int in8, int in9) {
            object[] results = this.Invoke("vipCluser", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7,
                        in8,
                        in9});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void vipCluserAsync(string in0, string in1, string in2, string in3, int in4, string in5, string in6, int in7, int in8, int in9) {
            this.vipCluserAsync(in0, in1, in2, in3, in4, in5, in6, in7, in8, in9, null);
        }
        
        /// <remarks/>
        public void vipCluserAsync(string in0, string in1, string in2, string in3, int in4, string in5, string in6, int in7, int in8, int in9, object userState) {
            if ((this.vipCluserOperationCompleted == null)) {
                this.vipCluserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvipCluserOperationCompleted);
            }
            this.InvokeAsync("vipCluser", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7,
                        in8,
                        in9}, this.vipCluserOperationCompleted, userState);
        }
        
        private void OnvipCluserOperationCompleted(object arg) {
            if ((this.vipCluserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vipCluserCompleted(this, new vipCluserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string customDataRetrieveOperation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] string[] in1, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] string[] in2) {
            object[] results = this.Invoke("customDataRetrieveOperation", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void customDataRetrieveOperationAsync(string in0, string[] in1, string[] in2) {
            this.customDataRetrieveOperationAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void customDataRetrieveOperationAsync(string in0, string[] in1, string[] in2, object userState) {
            if ((this.customDataRetrieveOperationOperationCompleted == null)) {
                this.customDataRetrieveOperationOperationCompleted = new System.Threading.SendOrPostCallback(this.OncustomDataRetrieveOperationOperationCompleted);
            }
            this.InvokeAsync("customDataRetrieveOperation", new object[] {
                        in0,
                        in1,
                        in2}, this.customDataRetrieveOperationOperationCompleted, userState);
        }
        
        private void OncustomDataRetrieveOperationOperationCompleted(object arg) {
            if ((this.customDataRetrieveOperationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.customDataRetrieveOperationCompleted(this, new customDataRetrieveOperationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string customRegionChangeNotice([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, bool in1, bool in2) {
            object[] results = this.Invoke("customRegionChangeNotice", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void customRegionChangeNoticeAsync(string in0, bool in1, bool in2) {
            this.customRegionChangeNoticeAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void customRegionChangeNoticeAsync(string in0, bool in1, bool in2, object userState) {
            if ((this.customRegionChangeNoticeOperationCompleted == null)) {
                this.customRegionChangeNoticeOperationCompleted = new System.Threading.SendOrPostCallback(this.OncustomRegionChangeNoticeOperationCompleted);
            }
            this.InvokeAsync("customRegionChangeNotice", new object[] {
                        in0,
                        in1,
                        in2}, this.customRegionChangeNoticeOperationCompleted, userState);
        }
        
        private void OncustomRegionChangeNoticeOperationCompleted(object arg) {
            if ((this.customRegionChangeNoticeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.customRegionChangeNoticeCompleted(this, new customRegionChangeNoticeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string vipSearchByRealtion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, int in2, int in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in5, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in6, int in7, int in8, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in9, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in10, int in11) {
            object[] results = this.Invoke("vipSearchByRealtion", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7,
                        in8,
                        in9,
                        in10,
                        in11});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void vipSearchByRealtionAsync(string in0, string in1, int in2, int in3, string in4, string in5, string in6, int in7, int in8, string in9, string in10, int in11) {
            this.vipSearchByRealtionAsync(in0, in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, in11, null);
        }
        
        /// <remarks/>
        public void vipSearchByRealtionAsync(string in0, string in1, int in2, int in3, string in4, string in5, string in6, int in7, int in8, string in9, string in10, int in11, object userState) {
            if ((this.vipSearchByRealtionOperationCompleted == null)) {
                this.vipSearchByRealtionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvipSearchByRealtionOperationCompleted);
            }
            this.InvokeAsync("vipSearchByRealtion", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7,
                        in8,
                        in9,
                        in10,
                        in11}, this.vipSearchByRealtionOperationCompleted, userState);
        }
        
        private void OnvipSearchByRealtionOperationCompleted(object arg) {
            if ((this.vipSearchByRealtionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vipSearchByRealtionCompleted(this, new vipSearchByRealtionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string customDataUpadteOpreation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3) {
            object[] results = this.Invoke("customDataUpadteOpreation", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void customDataUpadteOpreationAsync(string in0, string in1, string in2, string in3) {
            this.customDataUpadteOpreationAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void customDataUpadteOpreationAsync(string in0, string in1, string in2, string in3, object userState) {
            if ((this.customDataUpadteOpreationOperationCompleted == null)) {
                this.customDataUpadteOpreationOperationCompleted = new System.Threading.SendOrPostCallback(this.OncustomDataUpadteOpreationOperationCompleted);
            }
            this.InvokeAsync("customDataUpadteOpreation", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.customDataUpadteOpreationOperationCompleted, userState);
        }
        
        private void OncustomDataUpadteOpreationOperationCompleted(object arg) {
            if ((this.customDataUpadteOpreationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.customDataUpadteOpreationCompleted(this, new customDataUpadteOpreationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string customDataDeleteOperation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] string[] in2) {
            object[] results = this.Invoke("customDataDeleteOperation", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void customDataDeleteOperationAsync(string in0, string in1, string[] in2) {
            this.customDataDeleteOperationAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void customDataDeleteOperationAsync(string in0, string in1, string[] in2, object userState) {
            if ((this.customDataDeleteOperationOperationCompleted == null)) {
                this.customDataDeleteOperationOperationCompleted = new System.Threading.SendOrPostCallback(this.OncustomDataDeleteOperationOperationCompleted);
            }
            this.InvokeAsync("customDataDeleteOperation", new object[] {
                        in0,
                        in1,
                        in2}, this.customDataDeleteOperationOperationCompleted, userState);
        }
        
        private void OncustomDataDeleteOperationOperationCompleted(object arg) {
            if ((this.customDataDeleteOperationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.customDataDeleteOperationCompleted(this, new customDataDeleteOperationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getTokenStream([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2) {
            object[] results = this.Invoke("getTokenStream", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getTokenStreamAsync(string in0, string in1, string in2) {
            this.getTokenStreamAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void getTokenStreamAsync(string in0, string in1, string in2, object userState) {
            if ((this.getTokenStreamOperationCompleted == null)) {
                this.getTokenStreamOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTokenStreamOperationCompleted);
            }
            this.InvokeAsync("getTokenStream", new object[] {
                        in0,
                        in1,
                        in2}, this.getTokenStreamOperationCompleted, userState);
        }
        
        private void OngetTokenStreamOperationCompleted(object arg) {
            if ((this.getTokenStreamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTokenStreamCompleted(this, new getTokenStreamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string hasKey([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
            object[] results = this.Invoke("hasKey", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void hasKeyAsync(string in0, string in1) {
            this.hasKeyAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void hasKeyAsync(string in0, string in1, object userState) {
            if ((this.hasKeyOperationCompleted == null)) {
                this.hasKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhasKeyOperationCompleted);
            }
            this.InvokeAsync("hasKey", new object[] {
                        in0,
                        in1}, this.hasKeyOperationCompleted, userState);
        }
        
        private void OnhasKeyOperationCompleted(object arg) {
            if ((this.hasKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.hasKeyCompleted(this, new hasKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getVisCache([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
            object[] results = this.Invoke("getVisCache", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getVisCacheAsync(string in0, string in1) {
            this.getVisCacheAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void getVisCacheAsync(string in0, string in1, object userState) {
            if ((this.getVisCacheOperationCompleted == null)) {
                this.getVisCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVisCacheOperationCompleted);
            }
            this.InvokeAsync("getVisCache", new object[] {
                        in0,
                        in1}, this.getVisCacheOperationCompleted, userState);
        }
        
        private void OngetVisCacheOperationCompleted(object arg) {
            if ((this.getVisCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVisCacheCompleted(this, new getVisCacheCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string vipGetInfoById([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, int in4) {
            object[] results = this.Invoke("vipGetInfoById", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void vipGetInfoByIdAsync(string in0, string in1, string in2, string in3, int in4) {
            this.vipGetInfoByIdAsync(in0, in1, in2, in3, in4, null);
        }
        
        /// <remarks/>
        public void vipGetInfoByIdAsync(string in0, string in1, string in2, string in3, int in4, object userState) {
            if ((this.vipGetInfoByIdOperationCompleted == null)) {
                this.vipGetInfoByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvipGetInfoByIdOperationCompleted);
            }
            this.InvokeAsync("vipGetInfoById", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, this.vipGetInfoByIdOperationCompleted, userState);
        }
        
        private void OnvipGetInfoByIdOperationCompleted(object arg) {
            if ((this.vipGetInfoByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vipGetInfoByIdCompleted(this, new vipGetInfoByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string getSuggest([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
            object[] results = this.Invoke("getSuggest", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSuggestAsync(string in0, string in1) {
            this.getSuggestAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void getSuggestAsync(string in0, string in1, object userState) {
            if ((this.getSuggestOperationCompleted == null)) {
                this.getSuggestOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSuggestOperationCompleted);
            }
            this.InvokeAsync("getSuggest", new object[] {
                        in0,
                        in1}, this.getSuggestOperationCompleted, userState);
        }
        
        private void OngetSuggestOperationCompleted(object arg) {
            if ((this.getSuggestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSuggestCompleted(this, new getSuggestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string deleteVisCache([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1) {
            object[] results = this.Invoke("deleteVisCache", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void deleteVisCacheAsync(string in0, string in1) {
            this.deleteVisCacheAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void deleteVisCacheAsync(string in0, string in1, object userState) {
            if ((this.deleteVisCacheOperationCompleted == null)) {
                this.deleteVisCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteVisCacheOperationCompleted);
            }
            this.InvokeAsync("deleteVisCache", new object[] {
                        in0,
                        in1}, this.deleteVisCacheOperationCompleted, userState);
        }
        
        private void OndeleteVisCacheOperationCompleted(object arg) {
            if ((this.deleteVisCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteVisCacheCompleted(this, new deleteVisCacheCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string reCreateTable() {
            object[] results = this.Invoke("reCreateTable", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void reCreateTableAsync() {
            this.reCreateTableAsync(null);
        }
        
        /// <remarks/>
        public void reCreateTableAsync(object userState) {
            if ((this.reCreateTableOperationCompleted == null)) {
                this.reCreateTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreCreateTableOperationCompleted);
            }
            this.InvokeAsync("reCreateTable", new object[0], this.reCreateTableOperationCompleted, userState);
        }
        
        private void OnreCreateTableOperationCompleted(object arg) {
            if ((this.reCreateTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.reCreateTableCompleted(this, new reCreateTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out")]
        public bool userDataChangedNotified([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, bool in1) {
            object[] results = this.Invoke("userDataChangedNotified", new object[] {
                        in0,
                        in1});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void userDataChangedNotifiedAsync(string in0, bool in1) {
            this.userDataChangedNotifiedAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void userDataChangedNotifiedAsync(string in0, bool in1, object userState) {
            if ((this.userDataChangedNotifiedOperationCompleted == null)) {
                this.userDataChangedNotifiedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuserDataChangedNotifiedOperationCompleted);
            }
            this.InvokeAsync("userDataChangedNotified", new object[] {
                        in0,
                        in1}, this.userDataChangedNotifiedOperationCompleted, userState);
        }
        
        private void OnuserDataChangedNotifiedOperationCompleted(object arg) {
            if ((this.userDataChangedNotifiedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.userDataChangedNotifiedCompleted(this, new userDataChangedNotifiedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string vipGetPartInfoById([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, int in4, int in5, int in6, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in7) {
            object[] results = this.Invoke("vipGetPartInfoById", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void vipGetPartInfoByIdAsync(string in0, string in1, string in2, string in3, int in4, int in5, int in6, string in7) {
            this.vipGetPartInfoByIdAsync(in0, in1, in2, in3, in4, in5, in6, in7, null);
        }
        
        /// <remarks/>
        public void vipGetPartInfoByIdAsync(string in0, string in1, string in2, string in3, int in4, int in5, int in6, string in7, object userState) {
            if ((this.vipGetPartInfoByIdOperationCompleted == null)) {
                this.vipGetPartInfoByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvipGetPartInfoByIdOperationCompleted);
            }
            this.InvokeAsync("vipGetPartInfoById", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7}, this.vipGetPartInfoByIdOperationCompleted, userState);
        }
        
        private void OnvipGetPartInfoByIdOperationCompleted(object arg) {
            if ((this.vipGetPartInfoByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vipGetPartInfoByIdCompleted(this, new vipGetPartInfoByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string vipSearchByObject([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, bool in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in5, int in6, int in7, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in8, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in9, int in10, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in11, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in12, int in13, int in14) {
            object[] results = this.Invoke("vipSearchByObject", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7,
                        in8,
                        in9,
                        in10,
                        in11,
                        in12,
                        in13,
                        in14});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void vipSearchByObjectAsync(string in0, bool in1, string in2, string in3, string in4, string in5, int in6, int in7, string in8, string in9, int in10, string in11, string in12, int in13, int in14) {
            this.vipSearchByObjectAsync(in0, in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, in11, in12, in13, in14, null);
        }
        
        /// <remarks/>
        public void vipSearchByObjectAsync(
                    string in0, 
                    bool in1, 
                    string in2, 
                    string in3, 
                    string in4, 
                    string in5, 
                    int in6, 
                    int in7, 
                    string in8, 
                    string in9, 
                    int in10, 
                    string in11, 
                    string in12, 
                    int in13, 
                    int in14, 
                    object userState) {
            if ((this.vipSearchByObjectOperationCompleted == null)) {
                this.vipSearchByObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvipSearchByObjectOperationCompleted);
            }
            this.InvokeAsync("vipSearchByObject", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7,
                        in8,
                        in9,
                        in10,
                        in11,
                        in12,
                        in13,
                        in14}, this.vipSearchByObjectOperationCompleted, userState);
        }
        
        private void OnvipSearchByObjectOperationCompleted(object arg) {
            if ((this.vipSearchByObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vipSearchByObjectCompleted(this, new vipSearchByObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out")]
        public bool changeSolrIndexRootPath([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, int in1) {
            object[] results = this.Invoke("changeSolrIndexRootPath", new object[] {
                        in0,
                        in1});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void changeSolrIndexRootPathAsync(string in0, int in1) {
            this.changeSolrIndexRootPathAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void changeSolrIndexRootPathAsync(string in0, int in1, object userState) {
            if ((this.changeSolrIndexRootPathOperationCompleted == null)) {
                this.changeSolrIndexRootPathOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangeSolrIndexRootPathOperationCompleted);
            }
            this.InvokeAsync("changeSolrIndexRootPath", new object[] {
                        in0,
                        in1}, this.changeSolrIndexRootPathOperationCompleted, userState);
        }
        
        private void OnchangeSolrIndexRootPathOperationCompleted(object arg) {
            if ((this.changeSolrIndexRootPathCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changeSolrIndexRootPathCompleted(this, new changeSolrIndexRootPathCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string vipSearchByResults(
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in3, 
                    bool in4, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in5, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in6, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in7, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in8, 
                    int in9, 
                    int in10, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in11, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in12, 
                    int in13, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in14, 
                    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in15, 
                    int in16, 
                    int in17, 
                    int in18) {
            object[] results = this.Invoke("vipSearchByResults", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7,
                        in8,
                        in9,
                        in10,
                        in11,
                        in12,
                        in13,
                        in14,
                        in15,
                        in16,
                        in17,
                        in18});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void vipSearchByResultsAsync(
                    string in0, 
                    string in1, 
                    string in2, 
                    string in3, 
                    bool in4, 
                    string in5, 
                    string in6, 
                    string in7, 
                    string in8, 
                    int in9, 
                    int in10, 
                    string in11, 
                    string in12, 
                    int in13, 
                    string in14, 
                    string in15, 
                    int in16, 
                    int in17, 
                    int in18) {
            this.vipSearchByResultsAsync(in0, in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, in11, in12, in13, in14, in15, in16, in17, in18, null);
        }
        
        /// <remarks/>
        public void vipSearchByResultsAsync(
                    string in0, 
                    string in1, 
                    string in2, 
                    string in3, 
                    bool in4, 
                    string in5, 
                    string in6, 
                    string in7, 
                    string in8, 
                    int in9, 
                    int in10, 
                    string in11, 
                    string in12, 
                    int in13, 
                    string in14, 
                    string in15, 
                    int in16, 
                    int in17, 
                    int in18, 
                    object userState) {
            if ((this.vipSearchByResultsOperationCompleted == null)) {
                this.vipSearchByResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvipSearchByResultsOperationCompleted);
            }
            this.InvokeAsync("vipSearchByResults", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7,
                        in8,
                        in9,
                        in10,
                        in11,
                        in12,
                        in13,
                        in14,
                        in15,
                        in16,
                        in17,
                        in18}, this.vipSearchByResultsOperationCompleted, userState);
        }
        
        private void OnvipSearchByResultsOperationCompleted(object arg) {
            if ((this.vipSearchByResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.vipSearchByResultsCompleted(this, new vipSearchByResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://wsdl.search.module.cloud.vip.com", ResponseNamespace="http://wsdl.search.module.cloud.vip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable=true)]
        public string setVisCache([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string in2) {
            object[] results = this.Invoke("setVisCache", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setVisCacheAsync(string in0, string in1, string in2) {
            this.setVisCacheAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void setVisCacheAsync(string in0, string in1, string in2, object userState) {
            if ((this.setVisCacheOperationCompleted == null)) {
                this.setVisCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetVisCacheOperationCompleted);
            }
            this.InvokeAsync("setVisCache", new object[] {
                        in0,
                        in1,
                        in2}, this.setVisCacheOperationCompleted, userState);
        }
        
        private void OnsetVisCacheOperationCompleted(object arg) {
            if ((this.setVisCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setVisCacheCompleted(this, new setVisCacheCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void vipMultiObjectSearchCompletedEventHandler(object sender, vipMultiObjectSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vipMultiObjectSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vipMultiObjectSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void vipCluserCompletedEventHandler(object sender, vipCluserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vipCluserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vipCluserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void customDataRetrieveOperationCompletedEventHandler(object sender, customDataRetrieveOperationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class customDataRetrieveOperationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal customDataRetrieveOperationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void customRegionChangeNoticeCompletedEventHandler(object sender, customRegionChangeNoticeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class customRegionChangeNoticeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal customRegionChangeNoticeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void vipSearchByRealtionCompletedEventHandler(object sender, vipSearchByRealtionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vipSearchByRealtionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vipSearchByRealtionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void customDataUpadteOpreationCompletedEventHandler(object sender, customDataUpadteOpreationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class customDataUpadteOpreationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal customDataUpadteOpreationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void customDataDeleteOperationCompletedEventHandler(object sender, customDataDeleteOperationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class customDataDeleteOperationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal customDataDeleteOperationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getTokenStreamCompletedEventHandler(object sender, getTokenStreamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTokenStreamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTokenStreamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void hasKeyCompletedEventHandler(object sender, hasKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class hasKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal hasKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getVisCacheCompletedEventHandler(object sender, getVisCacheCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVisCacheCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVisCacheCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void vipGetInfoByIdCompletedEventHandler(object sender, vipGetInfoByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vipGetInfoByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vipGetInfoByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getSuggestCompletedEventHandler(object sender, getSuggestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSuggestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSuggestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void deleteVisCacheCompletedEventHandler(object sender, deleteVisCacheCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteVisCacheCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteVisCacheCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void reCreateTableCompletedEventHandler(object sender, reCreateTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class reCreateTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal reCreateTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void userDataChangedNotifiedCompletedEventHandler(object sender, userDataChangedNotifiedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class userDataChangedNotifiedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal userDataChangedNotifiedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void vipGetPartInfoByIdCompletedEventHandler(object sender, vipGetPartInfoByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vipGetPartInfoByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vipGetPartInfoByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void vipSearchByObjectCompletedEventHandler(object sender, vipSearchByObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vipSearchByObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vipSearchByObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void changeSolrIndexRootPathCompletedEventHandler(object sender, changeSolrIndexRootPathCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changeSolrIndexRootPathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changeSolrIndexRootPathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void vipSearchByResultsCompletedEventHandler(object sender, vipSearchByResultsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class vipSearchByResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal vipSearchByResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setVisCacheCompletedEventHandler(object sender, setVisCacheCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setVisCacheCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setVisCacheCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591