//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3643
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VS2008.ConsoleApp.Test.HttpsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BizServiceException", Namespace="http://webservice.webp.huateng.com/")]
    [System.SerializableAttribute()]
    public partial class BizServiceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.webp.huateng.com/", ConfigurationName="HttpsService.IWebPService")]
    public interface IWebPService {
        
        // CODEGEN: 参数“response”需要其他方案信息，使用参数模式无法捕获这些信息。特定属性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VS2008.ConsoleApp.Test.HttpsService.BizServiceException), Action="", Name="BizServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        VS2008.ConsoleApp.Test.HttpsService.callWebPResponse callWebP(VS2008.ConsoleApp.Test.HttpsService.callWebP request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.webp.huateng.com/")]
    public partial class commonData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string activeStateField;
        
        private string activeTimeField;
        
        private string addressField;
        
        private string balanceField;
        
        private string bindStateField;
        
        private string birthdayField;
        
        private string cardMoneyField;
        
        private string cardNoField;
        
        private commonData[] cardTxnInfoField;
        
        private string cardTypeField;
        
        private commonData[] cardsInfoField;
        
        private string certNoField;
        
        private string certStateField;
        
        private string certTypeField;
        
        private string coprAddrField;
        
        private string corpNmField;
        
        private string corpTelField;
        
        private string corpZipCdField;
        
        private string cvv2Field;
        
        private string emailField;
        
        private string endDateField;
        
        private string endLineField;
        
        private string epayInField;
        
        private string freezesStateField;
        
        private string isEpayField;
        
        private string issueIdField;
        
        private string limitPayMoneyField;
        
        private string lockStateField;
        
        private string loginPwdField;
        
        private string lossStateField;
        
        private string merchantIdField;
        
        private string merchantNameField;
        
        private string mobileField;
        
        private string mobileStateField;
        
        private string newPwdField;
        
        private string nickNameField;
        
        private string oldPwdField;
        
        private string oldTransferNoField;
        
        private string orgCenterSysTimeField;
        
        private string orgCenterTraceNumField;
        
        private string orgCurrencyTypeField;
        
        private string orgRespCodeField;
        
        private string orgTranAmtField;
        
        private string orgTranCodeField;
        
        private string passwordField;
        
        private string productIdField;
        
        private string productNameField;
        
        private string queryTypeField;
        
        private string realNameField;
        
        private string respCodeField;
        
        private string serviceIdField;
        
        private string serviceNameField;
        
        private string sexField;
        
        private string startDateField;
        
        private string startLineField;
        
        private string totalLineField;
        
        private string tranCodeField;
        
        private string tranDateTimeField;
        
        private string tranTypeField;
        
        private string transMoneyField;
        
        private string transTimeField;
        
        private string transferNoField;
        
        private string userIdField;
        
        private string userStateField;
        
        private string valideCodeField;
        
        private string valideTimeField;
        
        private string zipCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string activeState {
            get {
                return this.activeStateField;
            }
            set {
                this.activeStateField = value;
                this.RaisePropertyChanged("activeState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string activeTime {
            get {
                return this.activeTimeField;
            }
            set {
                this.activeTimeField = value;
                this.RaisePropertyChanged("activeTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string bindState {
            get {
                return this.bindStateField;
            }
            set {
                this.bindStateField = value;
                this.RaisePropertyChanged("bindState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
                this.RaisePropertyChanged("birthday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string cardMoney {
            get {
                return this.cardMoneyField;
            }
            set {
                this.cardMoneyField = value;
                this.RaisePropertyChanged("cardMoney");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string cardNo {
            get {
                return this.cardNoField;
            }
            set {
                this.cardNoField = value;
                this.RaisePropertyChanged("cardNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cardTxnInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public commonData[] cardTxnInfo {
            get {
                return this.cardTxnInfoField;
            }
            set {
                this.cardTxnInfoField = value;
                this.RaisePropertyChanged("cardTxnInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string cardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
                this.RaisePropertyChanged("cardType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cardsInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public commonData[] cardsInfo {
            get {
                return this.cardsInfoField;
            }
            set {
                this.cardsInfoField = value;
                this.RaisePropertyChanged("cardsInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string certNo {
            get {
                return this.certNoField;
            }
            set {
                this.certNoField = value;
                this.RaisePropertyChanged("certNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string certState {
            get {
                return this.certStateField;
            }
            set {
                this.certStateField = value;
                this.RaisePropertyChanged("certState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string certType {
            get {
                return this.certTypeField;
            }
            set {
                this.certTypeField = value;
                this.RaisePropertyChanged("certType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string coprAddr {
            get {
                return this.coprAddrField;
            }
            set {
                this.coprAddrField = value;
                this.RaisePropertyChanged("coprAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string corpNm {
            get {
                return this.corpNmField;
            }
            set {
                this.corpNmField = value;
                this.RaisePropertyChanged("corpNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string corpTel {
            get {
                return this.corpTelField;
            }
            set {
                this.corpTelField = value;
                this.RaisePropertyChanged("corpTel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string corpZipCd {
            get {
                return this.corpZipCdField;
            }
            set {
                this.corpZipCdField = value;
                this.RaisePropertyChanged("corpZipCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string cvv2 {
            get {
                return this.cvv2Field;
            }
            set {
                this.cvv2Field = value;
                this.RaisePropertyChanged("cvv2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string endLine {
            get {
                return this.endLineField;
            }
            set {
                this.endLineField = value;
                this.RaisePropertyChanged("endLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string epayIn {
            get {
                return this.epayInField;
            }
            set {
                this.epayInField = value;
                this.RaisePropertyChanged("epayIn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string freezesState {
            get {
                return this.freezesStateField;
            }
            set {
                this.freezesStateField = value;
                this.RaisePropertyChanged("freezesState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string isEpay {
            get {
                return this.isEpayField;
            }
            set {
                this.isEpayField = value;
                this.RaisePropertyChanged("isEpay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string issueId {
            get {
                return this.issueIdField;
            }
            set {
                this.issueIdField = value;
                this.RaisePropertyChanged("issueId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string limitPayMoney {
            get {
                return this.limitPayMoneyField;
            }
            set {
                this.limitPayMoneyField = value;
                this.RaisePropertyChanged("limitPayMoney");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string lockState {
            get {
                return this.lockStateField;
            }
            set {
                this.lockStateField = value;
                this.RaisePropertyChanged("lockState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string loginPwd {
            get {
                return this.loginPwdField;
            }
            set {
                this.loginPwdField = value;
                this.RaisePropertyChanged("loginPwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string lossState {
            get {
                return this.lossStateField;
            }
            set {
                this.lossStateField = value;
                this.RaisePropertyChanged("lossState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string merchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("merchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string merchantName {
            get {
                return this.merchantNameField;
            }
            set {
                this.merchantNameField = value;
                this.RaisePropertyChanged("merchantName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string mobileState {
            get {
                return this.mobileStateField;
            }
            set {
                this.mobileStateField = value;
                this.RaisePropertyChanged("mobileState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string newPwd {
            get {
                return this.newPwdField;
            }
            set {
                this.newPwdField = value;
                this.RaisePropertyChanged("newPwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string nickName {
            get {
                return this.nickNameField;
            }
            set {
                this.nickNameField = value;
                this.RaisePropertyChanged("nickName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string oldPwd {
            get {
                return this.oldPwdField;
            }
            set {
                this.oldPwdField = value;
                this.RaisePropertyChanged("oldPwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string oldTransferNo {
            get {
                return this.oldTransferNoField;
            }
            set {
                this.oldTransferNoField = value;
                this.RaisePropertyChanged("oldTransferNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string orgCenterSysTime {
            get {
                return this.orgCenterSysTimeField;
            }
            set {
                this.orgCenterSysTimeField = value;
                this.RaisePropertyChanged("orgCenterSysTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string orgCenterTraceNum {
            get {
                return this.orgCenterTraceNumField;
            }
            set {
                this.orgCenterTraceNumField = value;
                this.RaisePropertyChanged("orgCenterTraceNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string orgCurrencyType {
            get {
                return this.orgCurrencyTypeField;
            }
            set {
                this.orgCurrencyTypeField = value;
                this.RaisePropertyChanged("orgCurrencyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string orgRespCode {
            get {
                return this.orgRespCodeField;
            }
            set {
                this.orgRespCodeField = value;
                this.RaisePropertyChanged("orgRespCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string orgTranAmt {
            get {
                return this.orgTranAmtField;
            }
            set {
                this.orgTranAmtField = value;
                this.RaisePropertyChanged("orgTranAmt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string orgTranCode {
            get {
                return this.orgTranCodeField;
            }
            set {
                this.orgTranCodeField = value;
                this.RaisePropertyChanged("orgTranCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("productName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string queryType {
            get {
                return this.queryTypeField;
            }
            set {
                this.queryTypeField = value;
                this.RaisePropertyChanged("queryType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string realName {
            get {
                return this.realNameField;
            }
            set {
                this.realNameField = value;
                this.RaisePropertyChanged("realName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
                this.RaisePropertyChanged("respCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
                this.RaisePropertyChanged("serviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=51)]
        public string serviceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("serviceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=52)]
        public string sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
                this.RaisePropertyChanged("sex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=53)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=54)]
        public string startLine {
            get {
                return this.startLineField;
            }
            set {
                this.startLineField = value;
                this.RaisePropertyChanged("startLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=55)]
        public string totalLine {
            get {
                return this.totalLineField;
            }
            set {
                this.totalLineField = value;
                this.RaisePropertyChanged("totalLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=56)]
        public string tranCode {
            get {
                return this.tranCodeField;
            }
            set {
                this.tranCodeField = value;
                this.RaisePropertyChanged("tranCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=57)]
        public string tranDateTime {
            get {
                return this.tranDateTimeField;
            }
            set {
                this.tranDateTimeField = value;
                this.RaisePropertyChanged("tranDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=58)]
        public string tranType {
            get {
                return this.tranTypeField;
            }
            set {
                this.tranTypeField = value;
                this.RaisePropertyChanged("tranType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=59)]
        public string transMoney {
            get {
                return this.transMoneyField;
            }
            set {
                this.transMoneyField = value;
                this.RaisePropertyChanged("transMoney");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=60)]
        public string transTime {
            get {
                return this.transTimeField;
            }
            set {
                this.transTimeField = value;
                this.RaisePropertyChanged("transTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=61)]
        public string transferNo {
            get {
                return this.transferNoField;
            }
            set {
                this.transferNoField = value;
                this.RaisePropertyChanged("transferNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=62)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=63)]
        public string userState {
            get {
                return this.userStateField;
            }
            set {
                this.userStateField = value;
                this.RaisePropertyChanged("userState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=64)]
        public string valideCode {
            get {
                return this.valideCodeField;
            }
            set {
                this.valideCodeField = value;
                this.RaisePropertyChanged("valideCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=65)]
        public string valideTime {
            get {
                return this.valideTimeField;
            }
            set {
                this.valideTimeField = value;
                this.RaisePropertyChanged("valideTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=66)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("zipCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="callWebP", WrapperNamespace="http://webservice.webp.huateng.com/", IsWrapped=true)]
    public partial class callWebP {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.webp.huateng.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VS2008.ConsoleApp.Test.HttpsService.commonData request;
        
        public callWebP() {
        }
        
        public callWebP(VS2008.ConsoleApp.Test.HttpsService.commonData request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="callWebPResponse", WrapperNamespace="http://webservice.webp.huateng.com/", IsWrapped=true)]
    public partial class callWebPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.webp.huateng.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VS2008.ConsoleApp.Test.HttpsService.commonData response;
        
        public callWebPResponse() {
        }
        
        public callWebPResponse(VS2008.ConsoleApp.Test.HttpsService.commonData response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IWebPServiceChannel : VS2008.ConsoleApp.Test.HttpsService.IWebPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WebPServiceClient : System.ServiceModel.ClientBase<VS2008.ConsoleApp.Test.HttpsService.IWebPService>, VS2008.ConsoleApp.Test.HttpsService.IWebPService {
        
        public WebPServiceClient() {
        }
        
        public WebPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VS2008.ConsoleApp.Test.HttpsService.callWebPResponse VS2008.ConsoleApp.Test.HttpsService.IWebPService.callWebP(VS2008.ConsoleApp.Test.HttpsService.callWebP request) {
            return base.Channel.callWebP(request);
        }
        
        public VS2008.ConsoleApp.Test.HttpsService.commonData callWebP(VS2008.ConsoleApp.Test.HttpsService.commonData request) {
            VS2008.ConsoleApp.Test.HttpsService.callWebP inValue = new VS2008.ConsoleApp.Test.HttpsService.callWebP();
            inValue.request = request;
            VS2008.ConsoleApp.Test.HttpsService.callWebPResponse retVal = ((VS2008.ConsoleApp.Test.HttpsService.IWebPService)(this)).callWebP(inValue);
            return retVal.response;
        }
    }
}
